### ISSUE TITLE
AOT compilation error

### ISSUE THREAD

**Issue by lanxuexing** [500tech/angular-tree-component#792]
I have used angular-tree-component in my project.It does work in version: 8.5.4.

It gives following error.
```vim
ERROR in ../node_modules/mobx/lib/api/flow.d.ts:9:83 - error TS2315: Type 'Generator' is not generic.

9 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
                                                                                    ~~~~~~~~~~~~~~~~~~~~~~
../node_modules/mobx/lib/api/flow.d.ts:9:108 - error TS2304: Cannot find name 'AsyncGenerator'.

9 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
```

# package.json
```json
"dependencies": {
    "angular-tree-component": "^8.5.2"
 }
```

# package-lock.json
```json
"angular-tree-component": {
      "version": "8.5.4",
      "resolved": "https://registry.npm.taobao.org/angular-tree-component/download/angular-tree-component-8.5.4.tgz",
      "integrity": "sha1-pBGjExDgaRPG5gUq+9FQiZKnKI8=",
      "requires": {
        "lodash": "^4.17.11",
        "mobx": "^4.15.1",
        "mobx-angular": "3.1.1"
      }
}
```

**Comment by JoshDoug** [comment]
I'm also running into this issue, I guess it's due to the issue mentioned in this mobx ticket, but I've not seen whether that's been fixed in Angular: https://github.com/mobxjs/mobx/issues/2193

**Comment by adamkleingit** [comment]
@JoshDoug but the issue you mentioned is about MobX 5.15, and here it is version 4.15.1

**Comment by adamkleingit** [comment]
@lanxuexing can you paste your entire package.json?
Or better yet - reproduce in a git repo?

**Comment by jbotamer** [comment]
@adamkleingit I am also running into this same issue. My understanding from the package-lock above states it will install ("mobx": "^4.15.1") and since 5.15.x is out won't it default to this version since it uses "^"?

**Comment by lanxuexing** [comment]
@adamkleingit 
# Steps to reproduce
[git repo](https://github.com/lanxuexing/tree-case)

# What I tried
- dev
```vim
npm run start
```
it's great!

- build prod
```vim
npm run build
```
it's wrong!

# Terminal Output
```vim
> ng build --prod


ERROR in node_modules/mobx/lib/api/flow.d.ts:9:83 - error TS2315: Type 'Generator' is not generic.

9 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
                                                                                    ~~~~~~~~~~~~~~~~~~~~~~
node_modules/mobx/lib/api/flow.d.ts:9:108 - error TS2304: Cannot find name 'AsyncGenerator'.

9 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
                                                                                                             ~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-case@0.0.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-case@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2020-02-13T19_04_02_953Z-debug.log
```

 Please help me with this, I'll be grateful.

**Comment by adamkleingit** [comment]
@lanxuexing - it works for me with the repo you posted.
Maybe you should remove node_modules and reinstall?

**Comment by lanxuexing** [comment]
@adamkleingit 
but it's wrong for me!

# Terminal Output

```bash
localhost:tree-case-master apple$ 
localhost:tree-case-master apple$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.25
Node: 12.13.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cli                      8.3.25
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
    
localhost:tree-case-master apple$ 
localhost:tree-case-master apple$ 
localhost:tree-case-master apple$ npm i

> fsevents@1.2.11 install /Users/apple/Downloads/tree-case-master/node_modules/@angular/compiler-cli/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.11 install /Users/apple/Downloads/tree-case-master/node_modules/karma/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.11 install /Users/apple/Downloads/tree-case-master/node_modules/watchpack/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.11 install /Users/apple/Downloads/tree-case-master/node_modules/webpack-dev-server/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@3.6.4 postinstall /Users/apple/Downloads/tree-case-master/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /Users/apple/Downloads/tree-case-master/node_modules/karma/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> @angular/cli@8.3.25 postinstall /Users/apple/Downloads/tree-case-master/node_modules/@angular/cli
> node ./bin/postinstall/script.js

added 1455 packages from 1070 contributors in 24.191s
localhost:tree-case-master apple$ 
localhost:tree-case-master apple$ 
localhost:tree-case-master apple$ 
localhost:tree-case-master apple$ 
localhost:tree-case-master apple$ 
localhost:tree-case-master apple$ npm run build

> tree-case@0.0.0 build /Users/apple/Downloads/tree-case-master
> ng build --prod


ERROR in node_modules/mobx/lib/api/flow.d.ts:9:83 - error TS2315: Type 'Generator' is not generic.

9 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
                                                                                    ~~~~~~~~~~~~~~~~~~~~~~
node_modules/mobx/lib/api/flow.d.ts:9:108 - error TS2304: Cannot find name 'AsyncGenerator'.

9 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
                                                                                                             ~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-case@0.0.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-case@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2020-02-15T07_03_58_189Z-debug.log
localhost:tree-case-master apple$ 
localhost:tree-case-master apple$ 
```

# angualr.json

I tried to change the compilation config. try rebuild, it's great!

```json
 {
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "tree-case": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/tree-case",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": false,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": false,   <--- 
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false,  <---
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "tree-case:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "tree-case:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "tree-case:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "tree-case:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "tree-case:serve:production"
            }
          }
        }
      }
    }},
  "defaultProject": "tree-case"
}
```

#  rebuild

```bash
localhost:tree-case apple$ 
localhost:tree-case apple$ 
localhost:tree-case apple$ npm run build

> tree-case@0.0.0 build /Users/apple/Desktop/tree-case
> ng build --prod

Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {0} runtime-es2015.7bce183f1ed5ae5f2249.js (runtime) 1.46 kB [entry] [rendered]
chunk {0} runtime-es5.7bce183f1ed5ae5f2249.js (runtime) 1.46 kB [entry] [rendered]
chunk {2} polyfills-es2015.6ea646076ae3bb4d27c1.js (polyfills) 61.9 kB [initial] [rendered]
chunk {3} polyfills-es5.48a536f08905d47d6c92.js (polyfills-es5) 134 kB [initial] [rendered]
chunk {1} main-es2015.9e0ed672dad65adbf503.js (main) 762 kB [initial] [rendered]
chunk {1} main-es5.9e0ed672dad65adbf503.js (main) 887 kB [initial] [rendered]
chunk {4} styles.59faa7873f31078e0160.css (styles) 3.87 kB [initial] [rendered]
Date: 2020-02-15T07:28:33.059Z - Hash: 9bb05a8349f97cfa4af9 - Time: 30737ms
localhost:tree-case apple$ 
localhost:tree-case apple$ 
```

Anytime! Thanks for the quick turnaround.

**Comment by adamkleingit** [comment]
Oops you're right, I missed the `--prod` flag. I get the same error.
But updating to angular-tree-component 8.5.6 solves the issue

**Comment by lanxuexing** [comment]
@adamkleingit 
Thanks a lot for your help. This would not have been possible without you.
