### ISSUE TITLE
Error: Unable to dynamically transpile ES module

### ISSUE THREAD

**Issue by klanglie** [500tech/angular-tree-component#484]
Since upgrading from 1.3.5 to v3 and updating systemjs to the latest version, I get the following error: 
systemjs.config.js:66 Error: Unable to dynamically transpile ES module
   A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
  Instantiating http://localhost/node_modules/angular2-tree-component/dist/angular2-tree-component.js
` "dependencies": {
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@angular/router": "5.0.3",
    "@angular/upgrade": "5.0.3",
    "angular2-tree-component": "3.1.0",
    "core-js": "2.5.1",
    "lodash": "4.17.4",
    "mydaterangepicker": "^4.1.11",
    "ng2-uploader": "2.0.0",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "systemjs": "0.20.19",
    "zone.js": "0.8.18"
  },
  "devDependencies": {}

systemjs: 

   var configuration = {
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: option.appPath,
            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

            'angular2-tree-component': 'npm:angular2-tree-component',
            'lodash': 'npm:lodash',
            'rxjs': 'npm:rxjs'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: option.appjs,
                defaultExtension: 'js'
            },
            'angular2-tree-component': {
                main: 'dist/angular2-tree-component.js',
                defaultExtension: 'js'
            },
            'rxjs': { main: 'Rx.js', defaultExtension: 'js' },
        }
    }

    System.config(configuration);
    System.import('app').catch(function (err) { console.error(err); });`
