### ISSUE TITLE
Problem after upgrading to 3.5.0: "(void 0) is not a function"

### ISSUE THREAD

**Issue by sveinfid** [500tech/angular-tree-component#292]
After upgrading from version 3.2.3 to 3.5.0 I receive a runtime error at the location where the "tree-root" directive is used, and the component does not work.

In Chrome I receive the following error:

`EXCEPTION: Uncaught (in promise): Error: Error in app/myComponent.component.html:25:4 caused by: (void 0) is not a function`

In Edge I receive the following error:

`Error in app/myComponent.component.html:25:4 caused by: Object expected`

**Comment by jb201** [comment]
Same issue here...

**Comment by irineu** [comment]
+1

**Comment by unnamed666** [comment]
same here :(

**Comment by adamkleingit** [comment]
Are you using SystemJS?

**Comment by unnamed666** [comment]
yes i'am

**Comment by ezzkht** [comment]
same issue here
https://github.com/500tech/angular-tree-component/issues/298
